<?php 

/*PRODUCTO_O_SERVICIO_9*/


$ROWotrosp = $proveedoresC->variableotrosprouctos();

$ROWotrosp1= array('enviarOTROS_PRODUCTOS' =>'enviarOTROS_PRODUCTOS');
$otrosproductosporcentaje = $conexion->contadorporcentaje($ROWotrosp,$ROWotrosp1);

$PRODUCTO_O_SERVICIO_9 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_9"])?$ROWotrosp["PRODUCTO_O_SERVICIO_9"]:"";
$PRODUCTO_O_SERVICIO_10 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_10"])?$ROWotrosp["PRODUCTO_O_SERVICIO_10"]:"";
$PRODUCTO_O_SERVICIO_11 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_11"])?$ROWotrosp["PRODUCTO_O_SERVICIO_11"]:"";
$PRODUCTO_O_SERVICIO_12 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_12"])?$ROWotrosp["PRODUCTO_O_SERVICIO_12"]:"";
$PRODUCTO_O_SERVICIO_13 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_13"])?$ROWotrosp["PRODUCTO_O_SERVICIO_13"]:"";
$PRODUCTO_O_SERVICIO_14 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_14"])?$ROWotrosp["PRODUCTO_O_SERVICIO_14"]:"";
$PRODUCTO_O_SERVICIO_15 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_15"])?$ROWotrosp["PRODUCTO_O_SERVICIO_15"]:"";
$PRODUCTO_O_SERVICIO_16 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_16"])?$ROWotrosp["PRODUCTO_O_SERVICIO_16"]:"";
$PRODUCTO_O_SERVICIO_17 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_17"])?$ROWotrosp["PRODUCTO_O_SERVICIO_17"]:"";
$PRODUCTO_O_SERVICIO_18 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_18"])?$ROWotrosp["PRODUCTO_O_SERVICIO_18"]:"";
$PRODUCTO_O_SERVICIO_19 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_19"])?$ROWotrosp["PRODUCTO_O_SERVICIO_19"]:"";
$PRODUCTO_O_SERVICIO_20 = isset($ROWotrosp["PRODUCTO_O_SERVICIO_20"])?$ROWotrosp["PRODUCTO_O_SERVICIO_20"]:"";
$enviarOTROS_PRODUCTOS = isset($ROWotrosp["enviarOTROS_PRODUCTOS"])?$ROWotrosp["enviarOTROS_PRODUCTOS"]:"";  


/*PRODUCTO_O_SERVICIO_9*/


$ROWDirEmpresa = $proveedoresC->variable_DIRECCIONP1();

$ROWotrosp12= array('VALIDADIRECCIONEP1' =>'VALIDADIRECCIONEP1');
$direcciondeempresaporcentaje =$conexion->contadorporcentaje($ROWDirEmpresa,$ROWotrosp12);

$P_NOMBRE_COMERCIAL_EMPRESA = isset($ROWDirEmpresa["P_NOMBRE_COMERCIAL_EMPRESA"])?$ROWDirEmpresa["P_NOMBRE_COMERCIAL_EMPRESA"]:"";
$P_NOMBRE_FISCAL_RS_EMPRESA = isset($ROWDirEmpresa["P_NOMBRE_FISCAL_RS_EMPRESA"])?$ROWDirEmpresa["P_NOMBRE_FISCAL_RS_EMPRESA"]:"";
$P_DIRECCION_FISCAL_EMPRESA = isset($ROWDirEmpresa["P_DIRECCION_FISCAL_EMPRESA"])?$ROWDirEmpresa["P_DIRECCION_FISCAL_EMPRESA"]:"";
$P_EDIFICIO_EMPRESA = isset($ROWDirEmpresa["P_EDIFICIO_EMPRESA"])?$ROWDirEmpresa["P_EDIFICIO_EMPRESA"]:"";
$P_CALLE_EMPRESA = isset($ROWDirEmpresa["P_CALLE_EMPRESA"])?$ROWDirEmpresa["P_CALLE_EMPRESA"]:"";
$P_NUMERO_EXTERIOR_EMPRESA = isset($ROWDirEmpresa["P_NUMERO_EXTERIOR_EMPRESA"])?$ROWDirEmpresa["P_NUMERO_EXTERIOR_EMPRESA"]:"";
$P_NUMERO_INTERIOR_EMPRESA = isset($ROWDirEmpresa["P_NUMERO_INTERIOR_EMPRESA"])?$ROWDirEmpresa["P_NUMERO_INTERIOR_EMPRESA"]:"";
$P_NUMERO_OFICINA_EMPRESA = isset($ROWDirEmpresa["P_NUMERO_OFICINA_EMPRESA"])?$ROWDirEmpresa["P_NUMERO_OFICINA_EMPRESA"]:"";
$P_COLONIA_EMPRESA = isset($ROWDirEmpresa["P_COLONIA_EMPRESA"])?$ROWDirEmpresa["P_COLONIA_EMPRESA"]:"";
$P_ALCALDIA_EMPRESA = isset($ROWDirEmpresa["P_ALCALDIA_EMPRESA"])?$ROWDirEmpresa["P_ALCALDIA_EMPRESA"]:"";
$P_C_P_EMPRESA = isset($ROWDirEmpresa["P_C_P_EMPRESA"])?$ROWDirEmpresa["P_C_P_EMPRESA"]:"";
$P_CIUDAD_EMPRESA = isset($ROWDirEmpresa["P_CIUDAD_EMPRESA"])?$ROWDirEmpresa["P_CIUDAD_EMPRESA"]:"";
$P_ESTADO_EMPRESA = isset($ROWDirEmpresa["P_ESTADO_EMPRESA"])?$ROWDirEmpresa["P_ESTADO_EMPRESA"]:"";
$P_PAIS_EMPRESA = isset($ROWDirEmpresa["P_PAIS_EMPRESA"])?$ROWDirEmpresa["P_PAIS_EMPRESA"]:"";
$dircasa11 = isset($ROWDirEmpresa["dircasa11"])?$ROWDirEmpresa["dircasa11"]:"";
$P_UBICACION_MAPA_1 = isset($ROWDirEmpresa["P_UBICACION_MAPA_1"])?$ROWDirEmpresa["P_UBICACION_MAPA_1"]:"";
$P_TELEFONO_1_EMPRESA = isset($ROWDirEmpresa["P_TELEFONO_1_EMPRESA"])?$ROWDirEmpresa["P_TELEFONO_1_EMPRESA"]:"";
$P_TELEFONO_2_EMPRESA = isset($ROWDirEmpresa["P_TELEFONO_2_EMPRESA"])?$ROWDirEmpresa["P_TELEFONO_2_EMPRESA"]:"";
$P_WHATSAPP_EMPRESA_1 = isset($ROWDirEmpresa["P_WHATSAPP_EMPRESA_1"])?$ROWDirEmpresa["P_WHATSAPP_EMPRESA_1"]:"";
$P_IMAIL_EMPRESA = isset($ROWDirEmpresa["P_IMAIL_EMPRESA"])?$ROWDirEmpresa["P_IMAIL_EMPRESA"]:"";
$P_PAGINA_WEB_EMPRESA = isset($ROWDirEmpresa["P_PAGINA_WEB_EMPRESA"])?$ROWDirEmpresa["P_PAGINA_WEB_EMPRESA"]:"";
$P_NOMBRE_APP_EMPRESA = isset($ROWDirEmpresa["P_NOMBRE_APP_EMPRESA"])?$ROWDirEmpresa["P_NOMBRE_APP_EMPRESA"]:"";

/* metodo pago proveedor*/

$ROWMETODOPP = $proveedoresC->variable_metodopagoproveedor();

$ROWotrosp12= array('VALIDAMETODOPAGO' =>'VALIDAMETODOPAGO');
$metododepagoporcentaje =$conexion->contadorporcentaje($ROWMETODOPP,$ROWotrosp12);



$P_RFC_MTDP = isset($ROWMETODOPP["P_RFC_MTDP"])?$ROWMETODOPP["P_RFC_MTDP"]:"";
$P_REGIMEN_FISCAL_MTDP = isset($ROWMETODOPP["P_REGIMEN_FISCAL_MTDP"])?$ROWMETODOPP["P_REGIMEN_FISCAL_MTDP"]:"";
$_P_METODO_DE_PAGO = isset($ROWMETODOPP["_P_METODO_DE_PAGO"])?$ROWMETODOPP["_P_METODO_DE_PAGO"]:"";
$P_FORMADE_PAGO = isset($ROWMETODOPP["P_FORMADE_PAGO"])?$ROWMETODOPP["P_FORMADE_PAGO"]:"";
$P_USO_CFDI = isset($ROWMETODOPP["P_USO_CFDI"])?$ROWMETODOPP["P_USO_CFDI"]:"";
$P_CONDICIONES_DE_PAGO = isset($ROWMETODOPP["P_CONDICIONES_DE_PAGO"])?$ROWMETODOPP["P_CONDICIONES_DE_PAGO"]:"";
$P_LIMITE_DE_CREDITO = isset($ROWMETODOPP["P_LIMITE_DE_CREDITO"])?$ROWMETODOPP["P_LIMITE_DE_CREDITO"]:"";
$P_FECHA_INICIO_NUEVO_CONVENIO = isset($ROWMETODOPP["P_FECHA_INICIO_NUEVO_CONVENIO"])?$ROWMETODOPP["P_FECHA_INICIO_NUEVO_CONVENIO"]:"";
$P_FECHA_FINALIZACION_CONVENIO = isset($ROWMETODOPP["P_FECHA_FINALIZACION_CONVENIO"])?$ROWMETODOPP["P_FECHA_FINALIZACION_CONVENIO"]:"";
$P_PORCENTAJE_COMISION_OTORGA = isset($ROWMETODOPP["P_PORCENTAJE_COMISION_OTORGA"])?$ROWMETODOPP["P_PORCENTAJE_COMISION_OTORGA"]:"";
$VALIDAMETODOPAGO = isset($ROWMETODOPP["VALIDAMETODOPAGO"])?$ROWMETODOPP["VALIDAMETODOPAGO"]:""; 



/* CONTACTO VENTAS */

/*
$ROWcontactp = $proveedoresC->variable_contactoventasP();

$ROWotrosp12= array('validaNOMBRECONTACTO1' =>'validaNOMBRECONTACTO1');
$contactosventasproveedoresporcentaje =$conexion->contadorporcentaje($ROWcontactp,$ROWotrosp12);


$P_NOMBRE_DEL_CONTACTO_V = isset($ROWcontactp["P_NOMBRE_DEL_CONTACTO_V"])?$ROWcontactp["P_NOMBRE_DEL_CONTACTO_V"]:"";
$P_NOMBRE_DEL_CONTACTO_V_2 = isset($ROWcontactp["P_NOMBRE_DEL_CONTACTO_V_2"])?$ROWcontactp["P_NOMBRE_DEL_CONTACTO_V_2"]:"";
$P_NOMBRE_DEL_CONTACTO_V_3 = isset($ROWcontactp["P_NOMBRE_DEL_CONTACTO_V_3"])?$ROWcontactp["P_NOMBRE_DEL_CONTACTO_V_3"]:"";
$P_NUMERO_CEL_CONTACTO_V = isset($ROWcontactp["P_NUMERO_CEL_CONTACTO_V"])?$ROWcontactp["P_NUMERO_CEL_CONTACTO_V"]:"";
$P_NUMERO_CEL_CONTACTO_V_2 = isset($ROWcontactp["P_NUMERO_CEL_CONTACTO_V_2"])?$ROWcontactp["P_NUMERO_CEL_CONTACTO_V_2"]:"";
$P_NUMERO_CEL_CONTACTO_V_3 = isset($ROWcontactp["P_NUMERO_CEL_CONTACTO_V_3"])?$ROWcontactp["P_NUMERO_CEL_CONTACTO_V_3"]:"";
$P_NUMERO_OFICINA_V = isset($ROWcontactp["P_NUMERO_OFICINA_V"])?$ROWcontactp["P_NUMERO_OFICINA_V"]:"";
$P_NUMERO_OFICINA_V_2 = isset($ROWcontactp["P_NUMERO_OFICINA_V_2"])?$ROWcontactp["P_NUMERO_OFICINA_V_2"]:"";
$P_NUMERO_OFICINA_V_3 = isset($ROWcontactp["P_NUMERO_OFICINA_V_3"])?$ROWcontactp["P_NUMERO_OFICINA_V_3"]:"";
$P_NUMERO_EXTENSION_V = isset($ROWcontactp["P_NUMERO_EXTENSION_V"])?$ROWcontactp["P_NUMERO_EXTENSION_V"]:"";
$P_NUMERO_EXTENSION_V_2 = isset($ROWcontactp["P_NUMERO_EXTENSION_V_2"])?$ROWcontactp["P_NUMERO_EXTENSION_V_2"]:"";
$P_NUMERO_EXTENSION_V_3 = isset($ROWcontactp["P_NUMERO_EXTENSION_V_3"])?$ROWcontactp["P_NUMERO_EXTENSION_V_3"]:"";
$P_IMAIL_CONTACTO_V = isset($ROWcontactp["P_IMAIL_CONTACTO_V"])?$ROWcontactp["P_IMAIL_CONTACTO_V"]:"";
$P_IMAIL_CONTACTO_V_2 = isset($ROWcontactp["P_IMAIL_CONTACTO_V_2"])?$ROWcontactp["P_IMAIL_CONTACTO_V_2"]:"";
$P_IMAIL_CONTACTO_EDE_V_3 = isset($ROWcontactp["P_IMAIL_CONTACTO_EDE_V_3"])?$ROWcontactp["P_IMAIL_CONTACTO_EDE_V_3"]:"";
$validaNOMBRECONTACTO1 = isset($ROWcontactp["validaNOMBRECONTACTO1"])?$ROWcontactp["validaNOMBRECONTACTO1"]:""; 
*/

/* CONTACTO VENTAS 2*/


$ROWcontactp2 = $proveedoresC->variable_contactoventasP2();

$ROWotrosp12= array('validaNOMBRECONTACTO2' =>'validaNOMBRECONTACTO2');
$contactosventasproveedoresporcentaje2 =$conexion->contadorporcentaje($ROWcontactp2,$ROWotrosp12);



$P_NOMBRE_DEL_CONTACTO_CF = isset($ROWcontactp2["P_NOMBRE_DEL_CONTACTO_CF"])?$ROWcontactp2["P_NOMBRE_DEL_CONTACTO_CF"]:"";
$P_NOMBRE_DEL_CONTACTO_NP = isset($ROWcontactp2["P_NOMBRE_DEL_CONTACTO_NP"])?$ROWcontactp2["P_NOMBRE_DEL_CONTACTO_NP"]:"";
$P_NOMBRE_DEL_CONTACTO_EDE = isset($ROWcontactp2["P_NOMBRE_DEL_CONTACTO_EDE"])?$ROWcontactp2["P_NOMBRE_DEL_CONTACTO_EDE"]:"";
$P_NUMERO_CEL_CONTACTO_CF = isset($ROWcontactp2["P_NUMERO_CEL_CONTACTO_CF"])?$ROWcontactp2["P_NUMERO_CEL_CONTACTO_CF"]:"";
$P_NUMERO_CEL_CONTACTO_NP = isset($ROWcontactp2["P_NUMERO_CEL_CONTACTO_NP"])?$ROWcontactp2["P_NUMERO_CEL_CONTACTO_NP"]:"";
$P_NUMERO_CEL_CONTACTO_EDE = isset($ROWcontactp2["P_NUMERO_CEL_CONTACTO_EDE"])?$ROWcontactp2["P_NUMERO_CEL_CONTACTO_EDE"]:"";
$P_NUMERO_OFICINA_CF = isset($ROWcontactp2["P_NUMERO_OFICINA_CF"])?$ROWcontactp2["P_NUMERO_OFICINA_CF"]:"";
$P_NUMERO_OFICINA_NP = isset($ROWcontactp2["P_NUMERO_OFICINA_NP"])?$ROWcontactp2["P_NUMERO_OFICINA_NP"]:"";
$P_NUMERO_OFICINA_EDE = isset($ROWcontactp2["P_NUMERO_OFICINA_EDE"])?$ROWcontactp2["P_NUMERO_OFICINA_EDE"]:"";
$P_NUMERO_EXTENSION_CF = isset($ROWcontactp2["P_NUMERO_EXTENSION_CF"])?$ROWcontactp2["P_NUMERO_EXTENSION_CF"]:"";
$P_NUMERO_EXTENSION_NP = isset($ROWcontactp2["P_NUMERO_EXTENSION_NP"])?$ROWcontactp2["P_NUMERO_EXTENSION_NP"]:"";
$P_NUMERO_EXTENSION_EDE = isset($ROWcontactp2["P_NUMERO_EXTENSION_EDE"])?$ROWcontactp2["P_NUMERO_EXTENSION_EDE"]:"";
$P_IMAIL_CONTACTO_CF = isset($ROWcontactp2["P_IMAIL_CONTACTO_CF"])?$ROWcontactp2["P_IMAIL_CONTACTO_CF"]:"";
$P_IMAIL_CONTACTO_NP = isset($ROWcontactp2["P_IMAIL_CONTACTO_NP"])?$ROWcontactp2["P_IMAIL_CONTACTO_NP"]:"";
$P_IMAIL_CONTACTO_EDE = isset($ROWcontactp2["P_IMAIL_CONTACTO_EDE"])?$ROWcontactp2["P_IMAIL_CONTACTO_EDE"]:"";
$validaNOMBRECONTACTO2 = isset($ROWcontactp2["validaNOMBRECONTACTO2"])?$ROWcontactp2["validaNOMBRECONTACTO2"]:"";

/* CONTACTO VENTAS 2*/


$ROWcontactp3 = $proveedoresC->variable_contactoventasP3();

$ROWotrosp12= array('validaNOMBRECONTACTO3' =>'validaNOMBRECONTACTO3');
$contactosventasproveedoresporcentaje3 =$conexion->contadorporcentaje($ROWcontactp3,$ROWotrosp12);


$P_NOMBRE_DEL_CONTACTO_CF_2 = isset($ROWcontactp3["P_NOMBRE_DEL_CONTACTO_CF_2"])?$ROWcontactp3["P_NOMBRE_DEL_CONTACTO_CF_2"]:"";
$P_NOMBRE_DEL_CONTACTO_NP_2 = isset($ROWcontactp3["P_NOMBRE_DEL_CONTACTO_NP_2"])?$ROWcontactp3["P_NOMBRE_DEL_CONTACTO_NP_2"]:"";
$P_NOMBRE_DEL_CONTACTO_EDE_2 = isset($ROWcontactp3["P_NOMBRE_DEL_CONTACTO_EDE_2"])?$ROWcontactp3["P_NOMBRE_DEL_CONTACTO_EDE_2"]:"";
$P_NUMERO_CEL_CONTACTO_CF_2 = isset($ROWcontactp3["P_NUMERO_CEL_CONTACTO_CF_2"])?$ROWcontactp3["P_NUMERO_CEL_CONTACTO_CF_2"]:"";
$P_NUMERO_CEL_CONTACTO_NP_2 = isset($ROWcontactp3["P_NUMERO_CEL_CONTACTO_NP_2"])?$ROWcontactp3["P_NUMERO_CEL_CONTACTO_NP_2"]:"";
$P_NUMERO_CEL_CONTACTO_EDE_2 = isset($ROWcontactp3["P_NUMERO_CEL_CONTACTO_EDE_2"])?$ROWcontactp3["P_NUMERO_CEL_CONTACTO_EDE_2"]:"";
$P_NUMERO_OFICINA_CF_2 = isset($ROWcontactp3["P_NUMERO_OFICINA_CF_2"])?$ROWcontactp3["P_NUMERO_OFICINA_CF_2"]:"";
$P_NUMERO_OFICINA_NP_2 = isset($ROWcontactp3["P_NUMERO_OFICINA_NP_2"])?$ROWcontactp3["P_NUMERO_OFICINA_NP_2"]:"";
$P_NUMERO_OFICINA_EDE_2 = isset($ROWcontactp3["P_NUMERO_OFICINA_EDE_2"])?$ROWcontactp3["P_NUMERO_OFICINA_EDE_2"]:"";
$P_NUMERO_EXTENSION_CF_2 = isset($ROWcontactp3["P_NUMERO_EXTENSION_CF_2"])?$ROWcontactp3["P_NUMERO_EXTENSION_CF_2"]:"";
$P_NUMERO_EXTENSION_NP_2 = isset($ROWcontactp3["P_NUMERO_EXTENSION_NP_2"])?$ROWcontactp3["P_NUMERO_EXTENSION_NP_2"]:"";
$P_NUMERO_EXTENSION_EDE_2 = isset($ROWcontactp3["P_NUMERO_EXTENSION_EDE_2"])?$ROWcontactp3["P_NUMERO_EXTENSION_EDE_2"]:"";
$P_IMAIL_CONTACTO_CF_2 = isset($ROWcontactp3["P_IMAIL_CONTACTO_CF_2"])?$ROWcontactp3["P_IMAIL_CONTACTO_CF_2"]:"";
$P_IMAIL_CONTACTO_NP_2 = isset($ROWcontactp3["P_IMAIL_CONTACTO_NP_2"])?$ROWcontactp3["P_IMAIL_CONTACTO_NP_2"]:"";
$P_IMAIL_CONTACTO_EDE_2 = isset($ROWcontactp3["P_IMAIL_CONTACTO_EDE_2"])?$ROWcontactp3["P_IMAIL_CONTACTO_EDE_2"]:"";
$validaNOMBRECONTACTO3 = isset($ROWcontactp3["validaNOMBRECONTACTO3"])?$ROWcontactp3["validaNOMBRECONTACTO3"]:""; 




/* INFORMACION PRODUCTOS SERVICIOS */

$ROWprodservicios = $proveedoresC->variable_productosservicios();

$ROWotrosp12= array('validaINFOPRODSERV' =>'validaINFOPRODSERV', 'CALIFICACIONPSG' => 'CALIFICACIONPSG', 'CALIFICACION_TR' => 'CALIFICACION_TR',
 'MOTIVO_CALIFICACION' => 'MOTIVO_CALIFICACION', 'PFECHA_ULTIMACOMPRA' =>'PFECHA_ULTIMACOMPRA', 'PFECHA_ACTUA_DOCUM' => 'PFECHA_ACTUA_DOCUM');
$informacionproductosserviciosporcentaje =$conexion->contadorporcentaje($ROWprodservicios,$ROWotrosp12);




$PROVEEDOR_DE_EPC = isset($ROWprodservicios["PROVEEDOR_DE_EPC"])?$ROWprodservicios["PROVEEDOR_DE_EPC"]:"";
$PROVEEDOR_DE_INNOVAC = isset($ROWprodservicios["PROVEEDOR_DE_INNOVAC"])?$ROWprodservicios["PROVEEDOR_DE_INNOVAC"]:"";
$PROVEEDOR_DE_JUST = isset($ROWprodservicios["PROVEEDOR_DE_JUST"])?$ROWprodservicios["PROVEEDOR_DE_JUST"]:"";
$CALIFICACIONPSG = isset($ROWprodservicios["CALIFICACIONPSG"])?$ROWprodservicios["CALIFICACIONPSG"]:"";
$CALIFICACION_TR = isset($ROWprodservicios["CALIFICACION_TR"])?$ROWprodservicios["CALIFICACION_TR"]:"";
$MOTIVO_CALIFICACION = isset($ROWprodservicios["MOTIVO_CALIFICACION"])?$ROWprodservicios["MOTIVO_CALIFICACION"]:"";
$CIUDAD_SERVICIO = isset($ROWprodservicios["CIUDAD_SERVICIO"])?$ROWprodservicios["CIUDAD_SERVICIO"]:"";
$PAIS_SERVICIO = isset($ROWprodservicios["PAIS_SERVICIO"])?$ROWprodservicios["PAIS_SERVICIO"]:"";
$PFECHA_ULTIMACOMPRA = isset($ROWprodservicios["PFECHA_ULTIMACOMPRA"])?$ROWprodservicios["PFECHA_ULTIMACOMPRA"]:"";
$PFECHA_ACTUA_DOCUM = isset($ROWprodservicios["PFECHA_ACTUA_DOCUM"])?$ROWprodservicios["PFECHA_ACTUA_DOCUM"]:"";
$PCONTACTADO_POR = isset($ROWprodservicios["PCONTACTADO_POR"])?$ROWprodservicios["PCONTACTADO_POR"]:"";
$P_OTRO = isset($ROWprodservicios["P_OTRO"])?$ROWprodservicios["P_OTRO"]:"";
$PLIGA_FOTOS_VIDEOS = isset($ROWprodservicios["PLIGA_FOTOS_VIDEOS"])?$ROWprodservicios["PLIGA_FOTOS_VIDEOS"]:"";
$PRODUCTO_O_SERVICIO = isset($ROWprodservicios["PRODUCTO_O_SERVICIO"])?$ROWprodservicios["PRODUCTO_O_SERVICIO"]:"";
$PRODUCTO_O_SERVICIO_2 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_2"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_2"]:"";
$PRODUCTO_O_SERVICIO_3 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_3"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_3"]:"";
$PRODUCTO_O_SERVICIO_4 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_4"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_4"]:"";
$PRODUCTO_O_SERVICIO_5 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_5"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_5"]:"";
$PRODUCTO_O_SERVICIO_6 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_6"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_6"]:"";
$PRODUCTO_O_SERVICIO_7 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_7"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_7"]:"";
$PRODUCTO_O_SERVICIO_8 = isset($ROWprodservicios["PRODUCTO_O_SERVICIO_8"])?$ROWprodservicios["PRODUCTO_O_SERVICIO_8"]:"";
$F_PPRESENTACION = isset($ROWprodservicios["F_PPRESENTACION"])?$ROWprodservicios["F_PPRESENTACION"]:"";
$F_PFOTOS_PRODUCTOS = isset($ROWprodservicios["F_PFOTOS_PRODUCTOS"])?$ROWprodservicios["F_PFOTOS_PRODUCTOS"]:"";


/* INFORMACION PRODUCTOS SERVICIOS */

$ROWdoctos = $proveedoresC->variablesadjuntosproveedor();

$ROWotrosp12= array('validaINFOPRODSERV' =>'validaINFOPRODSERV',
'F_PADJUNTAR_OTRO_DOCUMENTO' =>'F_PADJUNTAR_OTRO_DOCUMENTO','F_PADJUNTAR_OTRO_DOCUMENTO_1' =>'F_PADJUNTAR_OTRO_DOCUMENTO_1','F_PADJUNTAR_OTRO_DOCUMENTO_2' =>'F_PADJUNTAR_OTRO_DOCUMENTO_2','F_PADJUNTAR_OTRO_DOCUMENTO_3' =>'F_PADJUNTAR_OTRO_DOCUMENTO_3');
$datosproveedoresadjuntos =$conexion->contadorporcentaje($ROWdoctos,$ROWotrosp12);


$F_PDESCARGAR_CONTRATO_PROVEEDORES = isset($ROWdoctos["F_PDESCARGAR_CONTRATO_PROVEEDORES"])?$ROWdoctos["F_PDESCARGAR_CONTRATO_PROVEEDORES"]:"";
$F_PADJUNTAR_CONTRATO_FIRMADO = isset($ROWdoctos["F_PADJUNTAR_CONTRATO_FIRMADO"])?$ROWdoctos["F_PADJUNTAR_CONTRATO_FIRMADO"]:"";
$F_PADJUNTAR_CONTRATO_FIRMADO_2 = isset($ROWdoctos["F_PADJUNTAR_CONTRATO_FIRMADO_2"])?$ROWdoctos["F_PADJUNTAR_CONTRATO_FIRMADO_2"]:"";
$F_PADJUNTAR_CONVENIOS = isset($ROWdoctos["F_PADJUNTAR_CONVENIOS"])?$ROWdoctos["F_PADJUNTAR_CONVENIOS"]:"";
$F_PADJUNTAR_CONSTANCIA_DE_SITUACION_FISCAL = isset($ROWdoctos["F_PADJUNTAR_CONSTANCIA_DE_SITUACION_FISCAL"])?$ROWdoctos["F_PADJUNTAR_CONSTANCIA_DE_SITUACION_FISCAL"]:"";
$F_PADJUNTAR_OPINION_CUMPLIMIENTO = isset($ROWdoctos["F_PADJUNTAR_OPINION_CUMPLIMIENTO"])?$ROWdoctos["F_PADJUNTAR_OPINION_CUMPLIMIENTO"]:"";
$F_PADJUNTAR_REGIMEN_FISCAL = isset($ROWdoctos["F_PADJUNTAR_REGIMEN_FISCAL"])?$ROWdoctos["F_PADJUNTAR_REGIMEN_FISCAL"]:"";
$F_PADJUNTAR_COMPROBANTE_DE_DOMICILIO = isset($ROWdoctos["F_PADJUNTAR_COMPROBANTE_DE_DOMICILIO"])?$ROWdoctos["F_PADJUNTAR_COMPROBANTE_DE_DOMICILIO"]:"";
$F_PADJUNTAR_ESTADO_CUENTA_BANCARIO = isset($ROWdoctos["F_PADJUNTAR_ESTADO_CUENTA_BANCARIO"])?$ROWdoctos["F_PADJUNTAR_ESTADO_CUENTA_BANCARIO"]:"";
$F_PADJUNTAR_ACTA_CONSTITUTIVA = isset($ROWdoctos["F_PADJUNTAR_ACTA_CONSTITUTIVA"])?$ROWdoctos["F_PADJUNTAR_ACTA_CONSTITUTIVA"]:"";
$F_PADJUNTAR_PODER_NOTARIAL_REPRESENTANTE_LEGAL = isset($ROWdoctos["F_PADJUNTAR_PODER_NOTARIAL_REPRESENTANTE_LEGAL"])?$ROWdoctos["F_PADJUNTAR_PODER_NOTARIAL_REPRESENTANTE_LEGAL"]:"";
$F_PADJUNTAR_IDENTIFICACION_REPRESENTANTE_LEGAL = isset($ROWdoctos["F_PADJUNTAR_IDENTIFICACION_REPRESENTANTE_LEGAL"])?$ROWdoctos["F_PADJUNTAR_IDENTIFICACION_REPRESENTANTE_LEGAL"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO = isset($ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO"])?$ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_1 = isset($ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_1"])?$ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_2 = isset($ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_2"])?$ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_2"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_3 = isset($ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_3"])?$ROWdoctos["F_PADJUNTAR_OTRO_DOCUMENTO_3"]:"";
$ADJUNTAR_CONTRATO_INFORMACION= isset($ROWdoctos["ADJUNTAR_CONTRATO_INFORMACION"])?$ROWdoctos["ADJUNTAR_CONTRATO_INFORMACION"]:"";




/* otros documentos */

$ROWotrodocto = $proveedoresC->variable_OTROSDOCUMENTOS();

$ROWotrosp12o= array('validaOTROSDOCUMENTOS' =>'validaOTROSDOCUMENTOS');
$datosOTROSDOCUMENTOS =$conexion->contadorporcentaje($ROWotrodocto,$ROWotrosp12o);


$F_PADJUNTAR_OTRO_DOCUMENTO_4_1 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_4_1"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_4_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_5_1 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_5_1"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_5_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_6_1 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_6_1"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_6_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_7_1 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_7_1"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_7_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_8_1 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_8_1"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_8_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_9_1 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_9_1"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_9_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_10_1 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_10_1"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_10_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_11_1 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_11_1"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_11_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_12_1 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_12_1"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_12_1"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_13_1 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_13_1"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_13_1"]:""; 
$F_PADJUNTAR_OTRO_DOCUMENTO_4 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_4"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_4"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_5 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_5"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_5"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_6 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_6"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_6"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_7 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_7"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_7"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_8 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_8"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_8"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_9 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_9"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_9"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_10 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_10"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_10"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_11 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_11"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_11"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_12 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_12"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_12"]:"";
$F_PADJUNTAR_OTRO_DOCUMENTO_13 = isset($ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_13"])?$ROWotrodocto["F_PADJUNTAR_OTRO_DOCUMENTO_13"]:""; 





/* DIR OFICINAS BODEGAS */

$DIROFICINASBODEGAS = $proveedoresC->variable_DIROFICINASBODEGAS();

$ROWotrosp12o= array('validaDIROFICINASBODEGAS' =>'validaDIROFICINASBODEGAS');
$datosDIROFICINASBODEGAS =$conexion->contadorporcentaje($DIROFICINASBODEGAS,$ROWotrosp12o);


$P_EDIFICIO_OSB = isset($DIROFICINASBODEGAS["P_EDIFICIO_OSB"])?$DIROFICINASBODEGAS["P_EDIFICIO_OSB"]:"";
$P_CALLE_OSB = isset($DIROFICINASBODEGAS["P_CALLE_OSB"])?$DIROFICINASBODEGAS["P_CALLE_OSB"]:"";
$P_NUMERO_EXTERIOR_OSB = isset($DIROFICINASBODEGAS["P_NUMERO_EXTERIOR_OSB"])?$DIROFICINASBODEGAS["P_NUMERO_EXTERIOR_OSB"]:"";
$P_NUMERO_INTERIOR_OSB = isset($DIROFICINASBODEGAS["P_NUMERO_INTERIOR_OSB"])?$DIROFICINASBODEGAS["P_NUMERO_INTERIOR_OSB"]:"";
$P_NUMERO_OFICINA_OSB = isset($DIROFICINASBODEGAS["P_NUMERO_OFICINA_OSB"])?$DIROFICINASBODEGAS["P_NUMERO_OFICINA_OSB"]:"";
$P_COLONIA_OSB = isset($DIROFICINASBODEGAS["P_COLONIA_OSB"])?$DIROFICINASBODEGAS["P_COLONIA_OSB"]:"";
$P_ALCALDIA_OSB = isset($DIROFICINASBODEGAS["P_ALCALDIA_OSB"])?$DIROFICINASBODEGAS["P_ALCALDIA_OSB"]:"";
$P_CP_OSB = isset($DIROFICINASBODEGAS["P_CP_OSB"])?$DIROFICINASBODEGAS["P_CP_OSB"]:"";
$P_CIUDAD_OSB = isset($DIROFICINASBODEGAS["P_CIUDAD_OSB"])?$DIROFICINASBODEGAS["P_CIUDAD_OSB"]:"";
$P_ESTADO_OSB = isset($DIROFICINASBODEGAS["P_ESTADO_OSB"])?$DIROFICINASBODEGAS["P_ESTADO_OSB"]:"";
$P_PAIS_OSB = isset($DIROFICINASBODEGAS["P_PAIS_OSB"])?$DIROFICINASBODEGAS["P_PAIS_OSB"]:"";
$validaDIROFICINASBODEGAS = isset($DIROFICINASBODEGAS["validaDIROFICINASBODEGAS"])?$DIROFICINASBODEGAS["validaDIROFICINASBODEGAS"]:"";
$P_UBICACION_MAPA_OSB = isset($DIROFICINASBODEGAS["P_UBICACION_MAPA_OSB"])?$DIROFICINASBODEGAS["P_UBICACION_MAPA_OSB"]:"";
$P_TELEFONO_OSB_1 = isset($DIROFICINASBODEGAS["P_TELEFONO_OSB_1"])?$DIROFICINASBODEGAS["P_TELEFONO_OSB_1"]:"";
$P_TELEFONO_OSB_2 = isset($DIROFICINASBODEGAS["P_TELEFONO_OSB_2"])?$DIROFICINASBODEGAS["P_TELEFONO_OSB_2"]:"";
$P_WHATSAPP_OSB_1 = isset($DIROFICINASBODEGAS["P_WHATSAPP_OSB_1"])?$DIROFICINASBODEGAS["P_WHATSAPP_OSB_1"]:"";
$P_NOMBRE_CONTACTO_OSB_1 = isset($DIROFICINASBODEGAS["P_NOMBRE_CONTACTO_OSB_1"])?$DIROFICINASBODEGAS["P_NOMBRE_CONTACTO_OSB_1"]:"";
$P_NUMERO_CEL_CONTACTO_OSB_1 = isset($DIROFICINASBODEGAS["P_NUMERO_CEL_CONTACTO_OSB_1"])?$DIROFICINASBODEGAS["P_NUMERO_CEL_CONTACTO_OSB_1"]:"";
$P_IMAIL_CONTACTO_OSB_1 = isset($DIROFICINASBODEGAS["P_IMAIL_CONTACTO_OSB_1"])?$DIROFICINASBODEGAS["P_IMAIL_CONTACTO_OSB_1"]:"";
$P_NUMERO_EXTENCION_OSB_1 = isset($DIROFICINASBODEGAS["P_NUMERO_EXTENCION_OSB_1"])?$DIROFICINASBODEGAS["P_NUMERO_EXTENCION_OSB_1"]:""; 





/* DATOS BANCARIOS 1 */

$DATOSBANCARIOS1 = $proveedoresC->variable_DATOSBANCARIOS1();

$ROWotrosp12o= array('validaDATOSBANCARIOS1' =>'validaDATOSBANCARIOS1');
$datosDATOSBANCARIOS1 =$conexion->contadorporcentaje($DATOSBANCARIOS1,$ROWotrosp12o);


$P_TIPO_DE_MONEDA_1 = isset($DATOSBANCARIOS1["P_TIPO_DE_MONEDA_1"])?$DATOSBANCARIOS1["P_TIPO_DE_MONEDA_1"]:"";
$P_INSTITUCION_FINANCIERA_1 = isset($DATOSBANCARIOS1["P_INSTITUCION_FINANCIERA_1"])?$DATOSBANCARIOS1["P_INSTITUCION_FINANCIERA_1"]:"";
$P_NUMERO_DE_CUENTA_DB_1 = isset($DATOSBANCARIOS1["P_NUMERO_DE_CUENTA_DB_1"])?$DATOSBANCARIOS1["P_NUMERO_DE_CUENTA_DB_1"]:"";
$P_NUMERO_CLABE_1 = isset($DATOSBANCARIOS1["P_NUMERO_CLABE_1"])?$DATOSBANCARIOS1["P_NUMERO_CLABE_1"]:"";
$P_NUMERO_DE_SUCURSAL_1 = isset($DATOSBANCARIOS1["P_NUMERO_DE_SUCURSAL_1"])?$DATOSBANCARIOS1["P_NUMERO_DE_SUCURSAL_1"]:"";
$P_NUMERO_IBAN_1 = isset($DATOSBANCARIOS1["P_NUMERO_IBAN_1"])?$DATOSBANCARIOS1["P_NUMERO_IBAN_1"]:"";
$P_NUMERO_CUENTA_SWIFT_1 = isset($DATOSBANCARIOS1["P_NUMERO_CUENTA_SWIFT_1"])?$DATOSBANCARIOS1["P_NUMERO_CUENTA_SWIFT_1"]:"";
$validaDATOSBANCARIOS1 = isset($DATOSBANCARIOS1["validaDATOSBANCARIOS1"])?$DATOSBANCARIOS1["validaDATOSBANCARIOS1"]:""; 


/* DATOS BANCARIOS 1 */

$ROWdatosbancarios2 = $proveedoresC->variable_DATOSBANCARIOS2();

$ROWotrosp12o= array('validaDATOSBANCARIOS2' =>'validaDATOSBANCARIOS2');
$datosporcentajeDATOSBANCARIOS2 =$conexion->contadorporcentaje($ROWdatosbancarios2,$ROWotrosp12o);

$P_TIPO_DE_MONEDA_2 = isset($ROWdatosbancarios2["P_TIPO_DE_MONEDA_2"])?$ROWdatosbancarios2["P_TIPO_DE_MONEDA_2"]:"";
$P_INSTITUCION_FINANCIERA_2 = isset($ROWdatosbancarios2["P_INSTITUCION_FINANCIERA_2"])?$ROWdatosbancarios2["P_INSTITUCION_FINANCIERA_2"]:"";
$P_NUMERO_DE_CUENTA_DB_2 = isset($ROWdatosbancarios2["P_NUMERO_DE_CUENTA_DB_2"])?$ROWdatosbancarios2["P_NUMERO_DE_CUENTA_DB_2"]:"";
$P_NUMERO_CLABE_2 = isset($ROWdatosbancarios2["P_NUMERO_CLABE_2"])?$ROWdatosbancarios2["P_NUMERO_CLABE_2"]:"";
$P_NUMERO_DE_SUCURSAL_2 = isset($ROWdatosbancarios2["P_NUMERO_DE_SUCURSAL_2"])?$ROWdatosbancarios2["P_NUMERO_DE_SUCURSAL_2"]:"";
$P_NUMERO_IBAN_2 = isset($ROWdatosbancarios2["P_NUMERO_IBAN_2"])?$ROWdatosbancarios2["P_NUMERO_IBAN_2"]:"";
$P_NUMERO_CUENTA_SWIFT_2 = isset($ROWdatosbancarios2["P_NUMERO_CUENTA_SWIFT_2"])?$ROWdatosbancarios2["P_NUMERO_CUENTA_SWIFT_2"]:"";
$validaDATOSBANCARIOS2 = isset($ROWdatosbancarios2["validaDATOSBANCARIOS2"])?$ROWdatosbancarios2["validaDATOSBANCARIOS2"]:"";  




/* REFERENCIAS COMERCIALES 1 */

$REFERENCIASCOMERCIALES1 = $proveedoresC->variable_REFERENCIASCOMERCIALES1();

$ROWotrosp12o= array('validaREFERENCIASCOMERCIALES1' =>'validaREFERENCIASCOMERCIALES1');
$datosREFERENCIASCOMERCIALES1 =$conexion->contadorporcentaje($REFERENCIASCOMERCIALES1,$ROWotrosp12o);




$P_NOMBRE_EMPRESA_RC_1 = isset($REFERENCIASCOMERCIALES1["P_NOMBRE_EMPRESA_RC_1"])?$REFERENCIASCOMERCIALES1["P_NOMBRE_EMPRESA_RC_1"]:"";
$P_NOMBRE_CONTACTO_RC_1 = isset($REFERENCIASCOMERCIALES1["P_NOMBRE_CONTACTO_RC_1"])?$REFERENCIASCOMERCIALES1["P_NOMBRE_CONTACTO_RC_1"]:"";
$P_CELULAR_CONTACTO_RC_1 = isset($REFERENCIASCOMERCIALES1["P_CELULAR_CONTACTO_RC_1"])?$REFERENCIASCOMERCIALES1["P_CELULAR_CONTACTO_RC_1"]:"";
$P_TELEFONO_EMPRESA_RC_1 = isset($REFERENCIASCOMERCIALES1["P_TELEFONO_EMPRESA_RC_1"])?$REFERENCIASCOMERCIALES1["P_TELEFONO_EMPRESA_RC_1"]:"";
$P_NUMERO_EXTENSION_RC_1 = isset($REFERENCIASCOMERCIALES1["P_NUMERO_EXTENSION_RC_1"])?$REFERENCIASCOMERCIALES1["P_NUMERO_EXTENSION_RC_1"]:"";
$P_IMAIL_CONTACTO_RC_1 = isset($REFERENCIASCOMERCIALES1["P_IMAIL_CONTACTO_RC_1"])?$REFERENCIASCOMERCIALES1["P_IMAIL_CONTACTO_RC_1"]:"";
$P_PAGINA_WEB_RC_1 = isset($REFERENCIASCOMERCIALES1["P_PAGINA_WEB_RC_1"])?$REFERENCIASCOMERCIALES1["P_PAGINA_WEB_RC_1"]:"";
$validaREFERENCIASCOMERCIALES1 = isset($REFERENCIASCOMERCIALES1["validaREFERENCIASCOMERCIALES1"])?$REFERENCIASCOMERCIALES1["validaREFERENCIASCOMERCIALES1"]:""; 




/* REFERENCIAS COMERCIALES 1 */

$REFERENCIASCOMERCIALES2 = $proveedoresC->variable_REFERENCIASCOMERCIALES2();

$ROWotrosp12o= array('validaREFERENCIASCOMERCIALES2' =>'validaREFERENCIASCOMERCIALES2');
$datosREFERENCIASCOMERCIALES2 =$conexion->contadorporcentaje($REFERENCIASCOMERCIALES2,$ROWotrosp12o);




$P_NOMBRE_EMPRESA_RC_2 = isset($REFERENCIASCOMERCIALES2["P_NOMBRE_EMPRESA_RC_2"])?$REFERENCIASCOMERCIALES2["P_NOMBRE_EMPRESA_RC_2"]:"";
$P_NOMBRE_CONTACTO_RC_2 = isset($REFERENCIASCOMERCIALES2["P_NOMBRE_CONTACTO_RC_2"])?$REFERENCIASCOMERCIALES2["P_NOMBRE_CONTACTO_RC_2"]:"";
$P_CELULAR_CONTACTO_RC_2 = isset($REFERENCIASCOMERCIALES2["P_CELULAR_CONTACTO_RC_2"])?$REFERENCIASCOMERCIALES2["P_CELULAR_CONTACTO_RC_2"]:"";
$P_TELEFONO_EMPRESA_RC_2 = isset($REFERENCIASCOMERCIALES2["P_TELEFONO_EMPRESA_RC_2"])?$REFERENCIASCOMERCIALES2["P_TELEFONO_EMPRESA_RC_2"]:"";
$P_NUMERO_EXTENSIO_CONTACTO_RC_2 = isset($REFERENCIASCOMERCIALES2["P_NUMERO_EXTENSIO_CONTACTO_RC_2"])?$REFERENCIASCOMERCIALES2["P_NUMERO_EXTENSIO_CONTACTO_RC_2"]:"";
$P_IMAIL_RC_2 = isset($REFERENCIASCOMERCIALES2["P_IMAIL_RC_2"])?$REFERENCIASCOMERCIALES2["P_IMAIL_RC_2"]:"";
$P_PAGINA_WEB_RC_2 = isset($REFERENCIASCOMERCIALES2["P_PAGINA_WEB_RC_2"])?$REFERENCIASCOMERCIALES2["P_PAGINA_WEB_RC_2"]:"";
$validaREFERENCIASCOMERCIALES2 = isset($REFERENCIASCOMERCIALES2["validaREFERENCIASCOMERCIALES2"])?$REFERENCIASCOMERCIALES2["validaREFERENCIASCOMERCIALES2"]:"";



/* REFERENCIAS COMERCIALES 1 */

$REFERENCIASCOMERCIALES3 = $proveedoresC->variable_REFERENCIASCOMERCIALES3();

$ROWotrosp12o= array('validaREFERENCIASCOMERCIALES3' =>'validaREFERENCIASCOMERCIALES3');
$datosREFERENCIASCOMERCIALES3 =$conexion->contadorporcentaje($REFERENCIASCOMERCIALES3,$ROWotrosp12o);




$P_NOMBRE_EMPRESA_RC_3 = isset($REFERENCIASCOMERCIALES3["P_NOMBRE_EMPRESA_RC_3"])?$REFERENCIASCOMERCIALES3["P_NOMBRE_EMPRESA_RC_3"]:"";
$P_NOMBRE_CONTACTO_RC_3 = isset($REFERENCIASCOMERCIALES3["P_NOMBRE_CONTACTO_RC_3"])?$REFERENCIASCOMERCIALES3["P_NOMBRE_CONTACTO_RC_3"]:"";
$P_CELULAR_CONTACTO_RC_3 = isset($REFERENCIASCOMERCIALES3["P_CELULAR_CONTACTO_RC_3"])?$REFERENCIASCOMERCIALES3["P_CELULAR_CONTACTO_RC_3"]:"";
$P_TELEFONO_EMPRESA_RC_3 = isset($REFERENCIASCOMERCIALES3["P_TELEFONO_EMPRESA_RC_3"])?$REFERENCIASCOMERCIALES3["P_TELEFONO_EMPRESA_RC_3"]:"";
$P_NUMERO_EXTENSION_RC_3 = isset($REFERENCIASCOMERCIALES3["P_NUMERO_EXTENSION_RC_3"])?$REFERENCIASCOMERCIALES3["P_NUMERO_EXTENSION_RC_3"]:"";
$P_IMAIL_RC_3 = isset($REFERENCIASCOMERCIALES3["P_IMAIL_RC_3"])?$REFERENCIASCOMERCIALES3["P_IMAIL_RC_3"]:"";
$P_PAGINA_WEB_RC_3 = isset($REFERENCIASCOMERCIALES3["P_PAGINA_WEB_RC_3"])?$REFERENCIASCOMERCIALES3["P_PAGINA_WEB_RC_3"]:"";
$validaREFERENCIASCOMERCIALES3 = isset($REFERENCIASCOMERCIALES3["validaREFERENCIASCOMERCIALES3"])?$REFERENCIASCOMERCIALES3["validaREFERENCIASCOMERCIALES3"]:""; 


